# Generated by Django 4.0.5 on 2022-06-30 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
